mysite/members/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

mysite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("counter", views.counter, name="counter"),
    path("oli", views.oli, name="oli"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/members/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/members/views.py
from django.shortcuts import render
from django.http import HttpResponse

def members(request):
    return HttpResponse("Hello world!")

mysite/polls/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Question
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def counter(request):
    template = loader.get_template('counter.html')
    context = {}
    return HttpResponse(template.render(context, request))

def oli(request):
    template = loader.get_template('oli.html')
    context = {}
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/polls/templates/counter.html
<!DOCTYPE html>
<html>
    <script>
        var counter = 0;
        function myFunction() {
            alert('Hello html world! Click counter: ' + counter);
            counter++;
        }
    </script>
    <body>
        <h1>Counter</h1>
        <div>
            <p>Hello, world. You're at the polls/counter.</p>
            <br>
            <button id='button1' style="background-color:red" onclick="myFunction()">Click me!</button>
        </div>
    </body>
</html>

mysite/polls/templates/oli.html
<!DOCTYPE html>
<html>
<body>
    <div class="cia">
    <label>Podaj Liczbę A</label><br>
    <input type="text" id="licz_a"><br>
    <label>Podaj Liczbę B</label><br>
    <input type="text" id="licz_b"><br>
    <label>Wybierz Działanie</label><br>
    <input type="radio" name="dzial" id="dod">+
    <input type="radio" name="dzial" id="ode">-
    <input type="radio" name="dzial" id="mno">*
    <input type="radio" name="dzial" id="dziel">:<br>
    <button onclick="oblicz()">Oblicz</button><br>
    <label>Wynik</label><br>
    <p id="wynik"></p>
    </div>
</body>

<script>
    function oblicz(){

        let a = parseFloat(document.getElementById("licz_a").value);
        let b = parseFloat(document.getElementById("licz_b").value);
        let dzial = document.querySelector('input[name="dzial"]:checked');

        if (isNaN(a) || isNaN(b)) {
            document.getElementById("wynik").innerHTML = "Wprowadź poprawne liczby";
            return;
        }
        if (a === 0 && dzial.id === "dziel") {
            document.getElementById("wynik").innerHTML = "Nie można dzielić przez zero";
            return;
        }
        if (b === 0 && dzial.id === "dziel") {
            document.getElementById("wynik").innerHTML = "Nie można dzielić przez zero";
            return;
        }

        let wynik;

        switch(dzial.id) {
            case 'dod':
                wynik = a + b;
                break;
            case 'ode':
                wynik = a - b;
                break;
            case 'mno':
                wynik = a * b;
                break;
            case 'dziel':
                wynik = a / b;
                break;
            default:
                wynik = "Wybierz działanie";
        }
    
        document.getElementById("wynik").innerHTML = wynik.toFixed(2);
    }
</script>
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}